markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: wqqpp007
author: "wqqpp007"
email: wqqpp007@gmail.com
name: "wqqpp007个人博客"

all_categories: [
["fb", "足球","/posts/zq.html"], 
["bb", "篮球","/posts/lq.html"],
["pp", "乒乓","/posts/ppq.html"], 
["ym", "羽毛球","/posts/ymq.html"],
["golf", "高尔夫","/posts/gefq.html"], 
["other", "其他","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
